### ISSUE TITLE
question: prevent multiple calls to cidr filter

### ISSUE THREAD

**Issue by geertn444** [logstash-plugins/logstash-filter-cidr#15]
Hello,

I want to match src_ip to multiple cidr matches. I have subnets collected in 20 files. However,i don't want to call cidr filter 20 times. From the moment a match is found, the following cidr filters don't have to be called anymore. Any idea how to do that ?
Do i need to match on a tag first ? like this:

if $tag="notfound" {
 cidr {
   network_path = "/a.txt"
   add_tag { site = "AAA" }
   remove_tag { notfound }
 }
if $tag="notfound" {
 cidr {
   network_path = "/b.txt"
   add_tag { site = "BBB" }
   remove_tag { notfound }
 }
}

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
