### ISSUE TITLE
Possibility to configure with a dictionary

### ISSUE THREAD

**Issue by tsouza** [logstash-plugins/logstash-filter-cidr#8]
There could be a way to configure it like the `translate` plugin, where you can define a dictionary/dictionary_path and a destination field to assign all the cidrs matched with it's assigned value, defined in the dictionary.

**Comment by fjodorr** [comment]
+1 This is what i'm looking for.

**Comment by jaredmcqueen** [comment]
this would be great too.  If I get around to coding this, I'll issue a pull request

**Comment by VictorCovalski** [comment]
I've never written a logstash plugin before. I'll try to add this feature asap since i'm needing it too.

**Comment by jaredmcqueen** [comment]
FYI, it seems that regex translates for CIDRs are *much* faster than using the ipaddr library

**Comment by jordansissel** [comment]
@jaredmcqueen I won't say no to something that speeds up this filter :)

**Comment by VictorCovalski** [comment]
Got it guys :), will update my repo this weekend with the updated code for a pull request.

**Comment by VictorCovalski** [comment]
@tsouza https://github.com/VictorCovalski/logstash-filter-cidr
It's working well for me. Let me know if there's any issue.

**Comment by tsouza** [comment]
@VictorCovalski did you send a PR?

**Comment by VictorCovalski** [comment]
@tsouza Just did, is it ok? Sorry I'm new to contributing with FOSS projects.

**Comment by magnusbaeck** [comment]
This was solved in #9 which will be released in v3.1.0 of the plugin.
